### ISSUE TITLE
CI flow image

### ISSUE THREAD

**Issue by astroshim** [NFLabs/zeppelin-ci#1]
![image](https://cloud.githubusercontent.com/assets/3348133/11337991/99530b3c-9234-11e5-89ba-118b0071bd84.png)

**Comment by Leemoonsoo** [comment]
요그림에서 NFL Nexus 는 뭔가요?

**Comment by astroshim** [comment]
@Leemoonsoo NFL Nexus 는 build속도 때문에 우리가 설치한 maven package repository 입니다. 
cloud에 설치되면 삭제해도 될것 같습니다.

**Comment by Leemoonsoo** [comment]
아파치에서 3rd party repo (예. Cloudera repo) 통해서 빌드 하는걸 못하게 하는데, 캐싱용도라면 NFL Nexus 말고 maven repo cache 등으로 표시하는게 더 좋을거 같습니다

**Comment by astroshim** [comment]
@Leemoonsoo 넵..그렇게 하는게 좋겠네요..

**Comment by cris83** [comment]
* CI Flow Image Update
![image](https://cloud.githubusercontent.com/assets/8110426/11357843/1f60503e-92af-11e5-8560-62c8d4d37489.png)
