### ISSUE TITLE
구조 개선 빌드 시험 - only one zeppelin container

### ISSUE THREAD

**Issue by cris83** [NFLabs/zeppelin-ci#21]
zeppelin container를 backend 별로 띄우지 않고, 하나만 띄워서 Backend 별 빌드를 모두 진행한다.

**Comment by cris83** [comment]
#### * zeppelin docker를 하나만 띄워서 3개의 Backend와 연동하기 위해 필요한 작업
- zeppelin container 생성시 --link 옵션이 backend별로 다르게 반영되어 있는 부분 처리
- backend별 zeppelin-env.sh등의 설정 파일 하나로 통합

  - backend에 해당하는 zeppelin-env.sh을 빌드 절차에 따라 다르게 반영 해주는 루틴 추가
  - yarn의 경우 Dockerfile에서 conf 디렉토리 반영 부분을 build.sh로 변경하여 yarn 빌드시점 적용하도록 수정

- Dockerfile 내용 하나로 통합

- build.sh 수정

 > buildstep으로 backend의 spark version별 start/stop을 제어하는 루틴 변경
 > spark running 관련 빌드 처리 루틴 변경

- Backends bootstrap.sh 수정

 > 각 Backend별 bootstrap.sh의 buildstep 처리 절차를 단독으로 뜨는 zeppelin container buildstep과 sync 작업

**Comment by astroshim** [comment]
- full build 는 한번만 진행하고 나머지는 backend test build 만 수행 해서 build time 을 비교 해봐야 할것 같습니다.

**Comment by cris83** [comment]
#### Modify Jenkins-Jod for Test

 - 하나의 job에서 back-zep container 을 실행햇으나, 이 구조를 back만 실행하게 변경한다.
 - 하나로 통한한 zeppelin container는 spark_standalone에서 실행 해준다.
 - 가장 먼저 빌드되는 item은 std부터 시작해서 mesos, yarn 순으로 진행 한다.

#### Issue
 - 3개의 backend container 생성시 각 유니크한 이름을 하나의 zeppelin container에서 모두 알아야 하는 문제가 있다. 이 부분에 대한 처리를 3개의 Job에서 할당 받는 build id로 구분했지만, mesos, stand, yarn의 build id가 모두 다르기 때문에, 하나의 job에서 모두 실행하도록 변경하여 build id를 동일하게 반영하게 한다.

**Comment by cris83** [comment]
##### 기존 구조와 one zeppelin container 구조의 빌드 시간 비교
* 3 mvn는 특정 구간에서 failure 발생으로 제외

* 기존 구조 : 3개의 Job에서 가장 오래된 시간 확인
![image](https://cloud.githubusercontent.com/assets/8110426/12111617/fb21d818-b3d9-11e5-86f8-aded0831b25c.png)

* one zeppelin container 구조
![image](https://cloud.githubusercontent.com/assets/8110426/12111631/243a992e-b3da-11e5-8886-3d6c7583e24d.png)

**Comment by cris83** [comment]
* one zeppelin container `.m2` directory 공유 옵션 제거 후 재시험

![image](https://cloud.githubusercontent.com/assets/8110426/12112949/135cf01c-b3e3-11e5-9c08-5b6a019c70a7.png)
