### ISSUE TITLE
admin list에 등록되지 않은 사용자의 PR 처리

### ISSUE THREAD

**Issue by cris83** [NFLabs/zeppelin-ci#26]
### admin list에 등록되지 않은 사용자의 PR 처리

- PR을 생성 한다.
- 생성한 PR에 admin list에 등록된 id로 `ok to test` comment 자동 등록된다.
- 이 후에 1회 push를 진행 하면, 자동으로 CI 빌드가 실행 된다.

**Comment by cris11** [comment]
##### screenshot

1. PR User
![image](https://cloud.githubusercontent.com/assets/16458180/12014952/699b753c-ad78-11e5-934e-d29c1fdb7154.png)

2. Running CI 
`ok to test`가 자동 등록되었을 때, Push한 결과 화면
![image](https://cloud.githubusercontent.com/assets/16458180/12014942/492191ba-ad78-11e5-902c-1a605e133240.png)

**Comment by cris11** [comment]
### 모든 PR-User에 대해서 자동 Build 하기 ( enhancement )
* 아래와 같이 Jenkins Job의 설정을 추가 해준다.
( GitHub Pull Request Builder - 고급 )

![image](https://cloud.githubusercontent.com/assets/16458180/12021326/faa6a790-adc8-11e5-93bb-3772b0afb0cd.png)

* 모든 PR에 대해 `asking` 없이 자동 빌드를 실행(webhook) 한다.

* Test Complete - admin list의 id의 추가 comment 없이 실행.

![image](https://cloud.githubusercontent.com/assets/16458180/12021350/52a54726-adc9-11e5-966d-e39cbaa5471d.png)
